"""The map-rotation resolution contract: a ``--maps`` flag value -> a list of ARENA TARGETS.

The SINGLE SOURCE of how a map-rotation request resolves to the ordered set of arena-target
strings (the ``Arenas/<name>.json`` paths Unity loads + echoes back as ``WallLayout.map_id``), so
the trainer and the evaluator share one definition. stdlib + :mod:`pathlib` + :mod:`json` only —
no numpy, no env, no torch.

The DEFAULT rotation is the curated 10-map set :data:`CURATED_ROTATION` defined right here — the
single source of truth for the training rotation (there is no on-disk config-wrapper dir anymore).
The arena GEOMETRY those targets name lives under ``unity/Assets/StreamingAssets/Arenas/`` and is
(re)generated by ``exp-configs/_generate_maps.py``; this constant is just the ordered curation of
which of those arenas the rotation plays.

The resolver returns ARENA-TARGET STRINGS end to end so the caller consumes one uniform type with
no wrapper -> ``arena_path`` indirection.

Resolution semantics (matches the CLI contract; with ``argparse`` ``nargs="*"`` the flag passed
with NO value yields ``[]``, while an ABSENT flag keeps ``default=None``):

* ``None`` (flag ABSENT) -> ``None``: no rotation (single-map mode).
* ``[]`` or ``[ALL_MAPS_SENTINEL]`` (flag passed with no value) -> :data:`CURATED_ROTATION`.
* a single entry that is a DIRECTORY -> every ``*.json`` map-config in it (SORTED) mapped to its
  ``arena_path`` (a dir of map-config wrappers still works as a rotation source).
* otherwise -> the explicit list of arena targets, VERBATIM IN THE GIVEN ORDER (not re-sorted);
  callers pass ``Arenas/<name>.json`` strings directly.
"""

from __future__ import annotations

import json
from pathlib import Path

__all__ = ["CURATED_ROTATION", "ALL_MAPS_SENTINEL", "resolve_map_rotation"]

# The curated training rotation: the ordered set of arena targets the rotation plays when the
# ``--maps`` flag is passed with no value. The order is alphabetical by arena name — the stable,
# deterministic order downstream code indexes the on-disk int ``map_id`` against (position in this
# list). The arena GEOMETRY is generated by ``exp-configs/_generate_maps.py``; this is the curation
# of which arenas to play. (The Arenas dir also holds ``custom1`` / ``default`` / ``nowin_test``,
# which are deliberately NOT in the rotation.)
CURATED_ROTATION: tuple[str, ...] = (
    "Arenas/center_block.json",
    "Arenas/central_cross.json",
    "Arenas/chokepoint.json",
    "Arenas/custom1_2021.json",
    "Arenas/diagonal_pillars.json",
    "Arenas/empty.json",
    "Arenas/four_pillars.json",
    "Arenas/opposing_l.json",
    "Arenas/ring_fragments.json",
    "Arenas/scattered.json",
)

# argparse const for the rotation flag used with no value -> rotate over CURATED_ROTATION.
ALL_MAPS_SENTINEL = "__all__"


def _arena_target_from_config(config_path: Path) -> str:
    """Read a map-config JSON and return its ``arena_path`` (the arena-target / echo string).

    Strict ``json`` (Python-parsed). Raises ``ValueError`` if the field is missing or not a string.
    """
    with open(config_path, encoding="utf-8") as fh:
        config = json.load(fh)
    arena = config.get("arena_path")
    if not isinstance(arena, str):
        raise ValueError(f"map config {config_path} has no string 'arena_path' (got {arena!r})")
    return arena


def resolve_map_rotation(values: list[str] | None) -> list[str] | None:
    """Resolve a ``--maps`` flag value into a list of ARENA TARGETS (or ``None``).

    See the module docstring for the precedence. Every returned entry is an arena-target string
    (``Arenas/<name>.json`` — what Unity loads via ``switch_arena`` and echoes back as
    ``WallLayout.map_id``); ``None`` means single-map mode (no rotation). The curated/empty case
    returns :data:`CURATED_ROTATION`; an explicit list passes its entries through verbatim; a single
    directory entry maps each of its sorted ``*.json`` configs to that config's ``arena_path``.
    """
    if values is None:
        return None
    if values == [] or values == [ALL_MAPS_SENTINEL]:
        return list(CURATED_ROTATION)
    if len(values) == 1 and Path(values[0]).is_dir():
        return [_arena_target_from_config(p) for p in sorted(Path(values[0]).glob("*.json"))]
    return list(values)
